language: r
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install(); covrpage::covrpage(update_badge = FALSE,vignette = TRUE)'
  - Rscript -e 'pkgdown::build_site()'

r_github_packages:
  - r-lib/pkgdown
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_PAT"
  keep-history: true
  local-dir: docs
  on:
    branch: master
