language: r
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e "devtools::install(); utils::getParseData(parse('tests/testthat/helper_functions.R'), includeText = TRUE); covrpage::covrpage(update_badge = FALSE,vignette = TRUE)"
