language: r
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e "devtools::install();install.packages('utils'); l <- list.files(recursive = TRUE,full.names = TRUE); l; p <- parse(l[101]);p;utils::getParseData(p);"

#utils::getParseData(parse(list.files(recursive = TRUE,full.names = TRUE)[101]),includeText = TRUE); covrpage::covrpage(update_badge = FALSE,vignette = TRUE)