language: r
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install(); list.files(recursive = TRUE,full.names = TRUE); utils::getParseData(parse(list.files(recursive = TRUE,full.names = TRUE)[101]),includeText = TRUE); covrpage::covrpage(update_badge = FALSE,vignette = TRUE)'
